import React from 'react';
import type { CSSProperties } from 'react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  Bell,
  Bookmark,
  Book,
  BookOpen,
  Bot,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  Clock3,
  Code,
  Command,
  Copy,
  CornerDownRight,
  Crosshair,
  Cpu,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Download,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileImage,
  FileJson,
  FileQuestion,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileType,
  Film,
  Filter,
  Fingerprint,
  Flag,
  Folder,
  FolderOpen,
  Gavel,
  Github,
  Globe,
  Grid,
  GripVertical,
  HardDrive,
  Hash,
  Heart,
  HelpCircle,
  Highlighter,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Landmark,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Link,
  Link2,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Microscope,
  Minimize2,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Navigation,
  Network,
  Newspaper,
  Package,
  Paperclip,
  Pause,
  Phone,
  Plane,
  Play,
  Plus,
  PlusCircle,
  Printer,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Save,
  ScanText,
  Scale,
  ScrollText,
  Search,
  SearchCheck,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldClose,
  Sidebar,
  SidebarClose,
  SkipBack,
  SkipForward,
  Sliders,
  SlidersHorizontal,
  Smile,
  SortAsc,
  SortDesc,
  Sparkles,
  Square,
  Star,
  Sun,
  Sunset,
  Table,
  Tag,
  Target,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Type,
  Umbrella,
  Undo,
  Undo2,
  Unlink,
  Unlock,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  VolumeX,
  Wifi,
  WifiOff,
  X,
  XCircle,
  BrainCircuit,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

const icons = {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  Bell,
  Bookmark,
  Book,
  BookOpen,
  Bot,
  BrainCircuit,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  Clock3,
  Code,
  Command,
  Copy,
  CornerDownRight,
  Crosshair,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Download,
  Cpu,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileImage,
  FileJson,
  FileQuestion,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileType,
  Film,
  Filter,
  Fingerprint,
  Flag,
  Folder,
  FolderOpen,
  Gavel,
  Github,
  Globe,
  Grid,
  GripVertical,
  HardDrive,
  Hash,
  Heart,
  HelpCircle,
  Highlighter,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Landmark,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Link,
  Link2,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Microscope,
  Minimize2,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Navigation,
  Network,
  Newspaper,
  Package,
  Paperclip,
  Pause,
  Phone,
  Plane,
  Play,
  Plus,
  PlusCircle,
  Printer,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Save,
  ScanText,
  Scale,
  ScrollText,
  Search,
  SearchCheck,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldClose,
  Sidebar,
  SidebarClose,
  SkipBack,
  SkipForward,
  Sliders,
  SlidersHorizontal,
  Smile,
  SortAsc,
  SortDesc,
  Sparkles,
  Square,
  Star,
  Sun,
  Sunset,
  Table,
  Tag,
  Target,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Type,
  Umbrella,
  Undo,
  Undo2,
  Unlink,
  Unlock,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  VolumeX,
  Server,
  Wifi,
  WifiOff,
  X,
  XCircle,
  ZoomIn,
  ZoomOut,
  Zap,
};

// Allow string icon names so the UI can evolve without constantly updating this file.
// Unknown icon names will fall back to a warning + null render.
export type IconName = keyof typeof icons | (string & Record<never, never>);

export interface IconProps {
  name: IconName;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  color?:
    | 'primary'
    | 'secondary'
    | 'success'
    | 'warning'
    | 'danger'
    | 'info'
    | 'white'
    | 'gray'
    | 'inherit'
    | 'black'
    | 'blue'
    | 'accent'
    | (string & Record<never, never>);
  className?: string;
  style?: CSSProperties;
  fill?: string;
  ariaLabel?: string;
  ariaHidden?: boolean;
}

const Icon: React.FC<IconProps> = ({
  name,
  size = 'md',
  color = 'white',
  className = '',
  style,
  fill,
  ariaLabel,
  ariaHidden = false,
}) => {
  const IconComponent = icons[name as keyof typeof icons];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found in local icon library`);
    return null;
  }

  const sizeClasses = {
    xs: 'w-3 h-3',
    sm: 'w-4 h-4',
    md: 'w-5 h-5',
    lg: 'w-6 h-6',
    xl: 'w-8 h-8',
  };

  const colorClasses = {
    primary: 'text-[var(--accent)]',
    secondary: 'text-[var(--accent-secondary)]',
    success: 'text-[var(--accent-success)]',
    warning: 'text-[var(--accent-warning)]',
    danger: 'text-[var(--accent-danger)]',
    info: 'text-[var(--accent)]',
    white: 'text-[var(--text-primary)]',
    gray: 'text-[var(--text-muted)]',
    black: 'text-[var(--bg-dark)]',
    blue: 'text-[var(--accent)]',
    accent: 'text-[var(--accent)]',
    inherit: '',
  };

  const resolvedColorClass =
    typeof color === 'string' && Object.prototype.hasOwnProperty.call(colorClasses, color)
      ? colorClasses[color as keyof typeof colorClasses]
      : '';
  const resolvedInlineColor =
    typeof color === 'string' && !Object.prototype.hasOwnProperty.call(colorClasses, color)
      ? color
      : undefined;

  const combinedClasses = `${sizeClasses[size]} ${resolvedColorClass} ${className} shrink-0`;

  return (
    <IconComponent
      className={combinedClasses}
      style={{ ...(resolvedInlineColor ? { color: resolvedInlineColor } : {}), ...style }}
      fill={fill}
      aria-label={ariaLabel}
      aria-hidden={ariaHidden}
    />
  );
};

export default Icon;
