// Generated by scripts/audit_black_book_pages.ts and visually checked against PDF page 25.
// These are PDF page numbers, not the exhibit's printed page numbers.
export const blackBookSourceSha256 =
  '4f8e111d7bd29039742de62e9f67cf5051b617e26a923117df323a5d2fb3c0de';
export const blackBookSourcePages: Record<string, number> = {
  da8044aa6936978e7e3cb6ed9dd2fde06ac731e52cced8e8c60942f8e0d743cb: 25,
};
